### ISSUE TITLE
CI/CD and stuff

### ISSUE THREAD

**Issue by alecive** [ScazLab/ros_speech2text#22]
As per title, I think that :

 * [x] we should add travis to this repo
 * [x] we shuold add the travis integration to the baxter_collaboration channel on slack
 * [x] we should add Docker as with the other repositories

And this would be a good training for @JakeBrawer (who I have assigned to this task). Just copy paste / take inspiration from https://github.com/ScazLab/human_robot_collaboration  and or https://github.com/ScazLab/baxter_tictactoe https://github.com/ScazLab/hrc_speech_prediction 

Good luck! You have one week :sunglasses:

**Comment by JakeBrawer** [comment]
Komm, süßer Tod

**Comment by alecive** [comment]
Memento mori

**Comment by JakeBrawer** [comment]
Why reopen?
