### ISSUE TITLE
Things to do Bis

### ISSUE THREAD

**Issue by alecive** [ScazLab/ros_speech2text#7]
* [x] Publish the list of available devices onto a param in the ros parameter server
* [x] Asyncronous call to the API (low priority)
* [x] Dynamic thresholding for filtering out loud but short noises
* [x] Parameter for dynamic thresholding in the parameter server and the launch file
* [x] Draft a first set of words to use as a context (to be put in the launch file)

**Comment by ken-cheng-valon** [comment]
Available devices are published onto rosparam /ros_speech2text/available_audio_device in an array, listed according to their index starting by 0
